language: node_js
node_js:
 - lts/*
script: 
 - npm run build

deploy: 
  provider: pages
  token: $GITHUB_TOKEN
  cleanup: false
  skip_cleanup: true
  keep_history: true
  local-dir: dist
  on:
    branch: master