# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with:
        persist-credentials: false
      - name: deploy
        run: |
          npm ci
          git checkout --orphan gh-pages
          npm run build
          git --work-tree dist add --all
          git --work-tree dist commit -m 'Deploy'
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
